name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          printf "Host ec2\n\tHostName ${{ secrets.EC2_HOST }}\n\tUser ${{ secrets.EC2_USER }}\n\tIdentityFile ~/.ssh/deploy_key\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Deploy to EC2
        run: |
          ssh ec2 "
            cd ~/aws_dir && \
            git pull origin main && \
            npm install && \
            npm run build && \
            pm2 restart ts-server || pm2 start index.js --name ts-server
          "
